### ISSUE TITLE
small typo in vignette?

### ISSUE THREAD

**Issue by capezza** [mfasiolo/qgam#32]
Should it be 
`wM_s95[i] = a*wM[i] + (1-a)*wM_s95[i-1]` instead of
`wM_s95[i] = a*wM[i] + (1-a)*wM_s95[i]`
?
https://github.com/mfasiolo/qgam/blob/e2fde727e3c7dfc38583ed02bc5e3fff1e9b8209/vignettes/qgam.Rmd#L368

**Comment by mfasiolo** [comment]
Yes, that's wrong! Addressed here e4f485897176bb0d98d4777ce3fa9723e0be3c71. Thanks!
