### ISSUE TITLE
Error for small n (if (abs(old.score - score) > score.scale * conv.tol))

### ISSUE THREAD

**Issue by florianhartig** [mfasiolo/qgam#33]
Hi Matteo,

I've been considering to switch from to qgam for the plots in DHARMa (see https://github.com/florianhartig/DHARMa/issues/53), but I have the problem that for small n, I tend to get the error message 

```
Error in if (abs(old.score - score) > score.scale * conv.tol) { : 
  missing value where TRUE/FALSE needed
```
Any ideas if this can be avoided?

**Comment by mfasiolo** [comment]
This is due to the loss smoothness getting too large in some cases, solved here 88f0d5834e3549b101e03062f88960fb1f82b830
