### ISSUE TITLE
Expand family in qgam

### ISSUE THREAD

**Issue by Alectoria** [mfasiolo/qgam#36]
This is a request for an enhancement: It would be great if qgam would have the same range of families as family.mgcv in gam, e.g. the beta regression family to fit true % data.

**Comment by mfasiolo** [comment]
Dear Victoria, note that `qgam` estimates quantile regression models, that is models where there is no parametric assumption on the distribution of the dependent variable, `y`. Hence, if you think that the response `y` follows a beta, gamma, Gaussian or any other distribution you should fit a GAM model `gam()` using `mgcv`, not a quantile GAM. With `qgam` you can model the distribution of `y` without making any such assumption, that is without specifying any family. That is why the `qgam` function does not have an argument called `family`. But maybe I am misunderstanding your request?
